// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/crud.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserWriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           *int32                 `protobuf:"varint,2,opt,name=age,proto3,oneof" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserWriteReq) Reset() {
	*x = UserWriteReq{}
	mi := &file_proto_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWriteReq) ProtoMessage() {}

func (x *UserWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWriteReq.ProtoReflect.Descriptor instead.
func (*UserWriteReq) Descriptor() ([]byte, []int) {
	return file_proto_crud_proto_rawDescGZIP(), []int{0}
}

func (x *UserWriteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserWriteReq) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

type UserReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReadReq) Reset() {
	*x = UserReadReq{}
	mi := &file_proto_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReadReq) ProtoMessage() {}

func (x *UserReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReadReq.ProtoReflect.Descriptor instead.
func (*UserReadReq) Descriptor() ([]byte, []int) {
	return file_proto_crud_proto_rawDescGZIP(), []int{1}
}

func (x *UserReadReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DatabaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrMessage    string                 `protobuf:"bytes,3,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseResp) Reset() {
	*x = DatabaseResp{}
	mi := &file_proto_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseResp) ProtoMessage() {}

func (x *DatabaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseResp.ProtoReflect.Descriptor instead.
func (*DatabaseResp) Descriptor() ([]byte, []int) {
	return file_proto_crud_proto_rawDescGZIP(), []int{2}
}

func (x *DatabaseResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DatabaseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DatabaseResp) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

var File_proto_crud_proto protoreflect.FileDescriptor

const file_proto_crud_proto_rawDesc = "" +
	"\n" +
	"\x10proto/crud.proto\x12\x04CRUD\"A\n" +
	"\fUserWriteReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x03age\x18\x02 \x01(\x05H\x00R\x03age\x88\x01\x01B\x06\n" +
	"\x04_age\"!\n" +
	"\vUserReadReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"b\n" +
	"\fDatabaseResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"errMessage\x18\x03 \x01(\tR\n" +
	"errMessage2\xca\x01\n" +
	"\x04CRUD\x120\n" +
	"\x06Create\x12\x12.CRUD.UserWriteReq\x1a\x12.CRUD.DatabaseResp\x12-\n" +
	"\x04Read\x12\x11.CRUD.UserReadReq\x1a\x12.CRUD.DatabaseResp\x120\n" +
	"\x06Update\x12\x12.CRUD.UserWriteReq\x1a\x12.CRUD.DatabaseResp\x12/\n" +
	"\x06Delete\x12\x11.CRUD.UserReadReq\x1a\x12.CRUD.DatabaseRespB\fZ\n" +
	"CRUD/protob\x06proto3"

var (
	file_proto_crud_proto_rawDescOnce sync.Once
	file_proto_crud_proto_rawDescData []byte
)

func file_proto_crud_proto_rawDescGZIP() []byte {
	file_proto_crud_proto_rawDescOnce.Do(func() {
		file_proto_crud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crud_proto_rawDesc), len(file_proto_crud_proto_rawDesc)))
	})
	return file_proto_crud_proto_rawDescData
}

var file_proto_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_crud_proto_goTypes = []any{
	(*UserWriteReq)(nil), // 0: CRUD.UserWriteReq
	(*UserReadReq)(nil),  // 1: CRUD.UserReadReq
	(*DatabaseResp)(nil), // 2: CRUD.DatabaseResp
}
var file_proto_crud_proto_depIdxs = []int32{
	0, // 0: CRUD.CRUD.Create:input_type -> CRUD.UserWriteReq
	1, // 1: CRUD.CRUD.Read:input_type -> CRUD.UserReadReq
	0, // 2: CRUD.CRUD.Update:input_type -> CRUD.UserWriteReq
	1, // 3: CRUD.CRUD.Delete:input_type -> CRUD.UserReadReq
	2, // 4: CRUD.CRUD.Create:output_type -> CRUD.DatabaseResp
	2, // 5: CRUD.CRUD.Read:output_type -> CRUD.DatabaseResp
	2, // 6: CRUD.CRUD.Update:output_type -> CRUD.DatabaseResp
	2, // 7: CRUD.CRUD.Delete:output_type -> CRUD.DatabaseResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_crud_proto_init() }
func file_proto_crud_proto_init() {
	if File_proto_crud_proto != nil {
		return
	}
	file_proto_crud_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crud_proto_rawDesc), len(file_proto_crud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crud_proto_goTypes,
		DependencyIndexes: file_proto_crud_proto_depIdxs,
		MessageInfos:      file_proto_crud_proto_msgTypes,
	}.Build()
	File_proto_crud_proto = out.File
	file_proto_crud_proto_goTypes = nil
	file_proto_crud_proto_depIdxs = nil
}
